#!/usr/bin/env python3
"""Regenerate the reviewed host helpers embedded in the executable."""
import base64
import json
from pathlib import Path
import sys
import zlib
root=Path(__file__).resolve().parents[1]
source='\n'.join((root/'tools/host'/p).read_text() for p in ['common.py','installer.py','ssh_pair.py','ssh_install.py','windows_sdk.py','entry.py'])
encoded=base64.b64encode(zlib.compress(source.encode(),9)).decode()
bootstrap="import base64,zlib;exec(compile(zlib.decompress(base64.b64decode('"+encoded+"')),'<hap-host-tools>','exec'))"
# Keep the Windows CreateProcess command line below its limit.
assert len(bootstrap)<28000,len(bootstrap)
lines=['package hapcli','','// Generated by scripts/embed-host-tools.py from reviewed tools/host/*.py.', 'public func embeddedHostTools(): String {']
chunks=[bootstrap[i:i+120] for i in range(0,len(bootstrap),120)]
lines+=['    '+json.dumps(x)+(' +' if i<len(chunks)-1 else '') for i,x in enumerate(chunks)]
lines+=['}','']
output='\n'.join(lines);path=root/'src/host_tools_embedded.cj'
if '--check' in sys.argv:
    assert path.read_text()==output,'embedded host tools are stale'
else:path.write_text(output)
print('Host helper embedding:',len(source),'source bytes;',len(bootstrap),'command bytes')
